update: snapshot creation wait

diff --git a/.github/workflows/github_create_scratch.yml b/.github/workflows/github_create_scratch.yml
--- a/.github/workflows/github_create_scratch.yml
+++ b/.github/workflows/github_create_scratch.yml
@@ -61,9 +61,28 @@ jobs:
           echo '{ "orgName":"${{ github.event.inputs.scratch_alias }}", "snapshot":"${{ github.event.inputs.snapshot_name }}" }' > project-snapshot-scratch-def.json
           cat project-snapshot-scratch-def.json
           sf org create snapshot --source-org ${{ github.event.inputs.source_org_id }} --target-dev-hub ${{ secrets.SFDX_USERNAME_PDEVHUB }} --name ${{ github.event.inputs.snapshot_name }} --description "${{ github.event.inputs.snapshot_description }}"
-          sf org get snapshot --snapshot ${{ github.event.inputs.snapshot_name }} --target-dev-hub ${{ secrets.SFDX_USERNAME_PDEVHUB }}
+          
+          #!/bin/bash
+          rerunInterval = 600
+          orgGetSnapshotStatus() {
+            sf org get snapshot --snapshot ${{ github.event.inputs.snapshot_name }} --target-dev-hub ${{ secrets.SFDX_USERNAME_PDEVHUB }} jq -r '.result.Status'
+          }
+          while true; do
+            getStatus=$(orgGetSnapshotStatus)
+            if ["$getStatus" == "Active"]; then
+              echo "Snapshot Creation: SUCCESS."
+              break
+            elif ["$getStatus" == "Error" || "$getStatus" == "null"]; then
+              echo "Snapshot Creation: FAIL"
+              exit 1
+            else
+            echo "Snapshot Creation: IN PROGRESS"
+              sleep $rerunInterval
+            fi
+          done
+
           sf org create scratch --set-default --definition-file config/project-snapshot-scratch-def.json --target-dev-hub ${{ secrets.SFDX_USERNAME_PDEVHUB }} --no-namespace --duration-days  ${{ github.event.inputs.scratch_duration_days }}  --wait 30 --description "${{ github.event.inputs.scratch_description }}" --admin-email ${{ github.event.inputs.scratch_email }} --alias ${{ github.event.inputs.scratch_alias }}
-      
+
       - name: Generate Password & Get Scratch Org Info
         id: genpwd
         if: ${{ steps.scratch.outcome == 'success' || steps.snapscratch.outcome == 'success' }}
